authors:
  bybatkhuu:
    name: Batkhuu Byambajav
    description: Creator, maintainer
    avatar: https://avatars.githubusercontent.com/bybatkhuu
    url: https://github.com/bybatkhuu
  BaratovSokhibjon:
    name: Sokhibjon Baratov
    description: Contributor
    avatar: https://avatars.githubusercontent.com/BaratovSokhibjon
    url: https://github.com/BaratovSokhibjon
